name: Build Release APK (No-Secrets)

on:
  workflow_dispatch:   # manual trigger saja

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Grant gradlew executable
      - name: Grant gradlew permission
        run: chmod +x ./gradlew

      # 4. (Opsional) Install NDK kalau pakai native lib
      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b

      # 5. Build release APK
        # Semua signing config sudah ada di build.gradle.kts (hardcoded)
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # 6. Upload artefak
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-no-env
          path: app/build/outputs/apk/release/*.apk

      - name: Upload ProGuard mapping (private)
  uses: actions/upload-artifact@v4
  with:
    name: mapping-${{ github.run_number }}
    path: app/build/outputs/mapping/release/mapping.txt
    retention-days: 30

